version: '3.8'

services:
  db_bet:
    image: postgres:latest
    container_name: db_bet
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  db_event:
    image: postgres:latest
    container_name: db_event
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5433'
  api_bet:
    build: .
    image: entry
    container_name: api_bet
    command: bash -c "uvicorn --app-dir bet_maker bet_app:app --host 0.0.0.0 --port 8085 --reload"
    ports:
      - "8085:8085"
    depends_on:
      - db_bet
    environment:
      - DB_HOST=db_bet
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
  api_event:
    image: entry
    container_name: api_event
    command: bash -c "uvicorn --app-dir line_provider event_app:app --host 0.0.0.0 --port 8086 --reload"
    ports:
      - "8086:8086"
    depends_on:
      - db_event
    environment:
      - DB_HOST=db_event
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mypassword
